# Generated by Django 5.2.8 on 2025-11-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_entity', models.CharField(max_length=120)),
                ('counterparty', models.CharField(max_length=120)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('style', models.CharField(default='FORWARD', max_length=20)),
                ('notional_currency', models.CharField(max_length=3)),
                ('notional_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('underlying', models.JSONField(default=list)),
                ('trade_date', models.DateField()),
                ('value_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('strike', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('requester_id', models.CharField(max_length=64)),
                ('approver_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('NeedsReapproval', 'Needs Reapproval'), ('Approved', 'Approved'), ('SentToCounterparty', 'Sent To Counterparty'), ('Executed', 'Executed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('trade_date__lte', models.F('value_date'))), name='trade_le_value'), models.CheckConstraint(condition=models.Q(('value_date__lte', models.F('delivery_date'))), name='value_le_delivery'), models.CheckConstraint(condition=models.Q(('state', 'Executed'), ('strike__isnull', True), _connector='OR'), name='strike_only_when_executed')],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Submit', 'Submit'), ('Approve', 'Approve'), ('Cancel', 'Cancel'), ('Update', 'Update'), ('SendToExecute', 'Send To Execute'), ('Book', 'Book')], max_length=32)),
                ('actor_user_id', models.CharField(max_length=64)),
                ('before_state', models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('NeedsReapproval', 'Needs Reapproval'), ('Approved', 'Approved'), ('SentToCounterparty', 'Sent To Counterparty'), ('Executed', 'Executed'), ('Cancelled', 'Cancelled')], max_length=32)),
                ('after_state', models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('NeedsReapproval', 'Needs Reapproval'), ('Approved', 'Approved'), ('SentToCounterparty', 'Sent To Counterparty'), ('Executed', 'Executed'), ('Cancelled', 'Cancelled')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='trades_approval.trade')),
            ],
        ),
        migrations.CreateModel(
            name='TradeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('PendingApproval', 'Pending Approval'), ('NeedsReapproval', 'Needs Reapproval'), ('Approved', 'Approved'), ('SentToCounterparty', 'Sent To Counterparty'), ('Executed', 'Executed'), ('Cancelled', 'Cancelled')], max_length=32)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user_id', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('Submit', 'Submit'), ('Approve', 'Approve'), ('Cancel', 'Cancel'), ('Update', 'Update'), ('SendToExecute', 'Send To Execute'), ('Book', 'Book')], max_length=32)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='trades_approval.trade')),
            ],
        ),
    ]
